from typing import Final

FREE_SPACE: Final = "FREE SPACE"

QUESTIONS: Final[list[str]] = [
    "uses dark mode everywhere",
    "prefers tabs over spaces",
    "has a mechanical keyboard",
    "uses Vim or Neovim keybindings",
    "has 50+ browser tabs open",
    "has a dotfiles repository",
    "writes commit messages with AI",
    "lives in the terminal",
    "has a favorite IDE theme",
    "uses Linux as a daily driver",
    "keeps a side project alive",
    "works from a coffee shop",
    "has strong opinions about semicolons",
    "adds tests before finalizing code",
    "debugs with console logs first",
    "has a custom Git alias",
    "reads release notes before upgrading",
    "has a local dev environment checklist",
    "uses multiple monitors",
    "has a favorite Stack Overflow answer",
    "owns a hoodie with a developer slogan",
    "has a love-hate relationship with TypeScript",
    "picks frameworks based on vibes",
    "has refactored a legacy codebase",
    "thinks 'it works on my machine' is a warning sign",
    "uses browser dev tools before the debugger",
    "would rather refactor than read docs",
    "has a favorite pair programming story",
    "drops a TODO and never looks back",
]
